/**
 * Generate a migration from the diff between the entities and a database.
 *
 *   node scripts/dist/migration-generate.js --name=AddFoo
 *
 * Flow (mirrors `typeorm migration:generate`, but programmatic — the CLI's own
 * TS loader chokes on legacy decorators under Node 24):
 *   1. bring the target DB up to date (same path as server boot),
 *   2. diff the entity metadata against it via SchemaBuilder.log(),
 *   3. write src/migrations/<timestamp>-<Name>.ts with up()/down() SQL,
 *   4. remind you to register the class in src/migrations/index.ts.
 *
 * Exit code 1 when there is nothing to generate (useful in CI).
 */
import 'dotenv/config'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function resolveName(): string {
  const arg = process.argv.find((a) => a.startsWith('--name='))
  const raw = arg ? arg.slice(7) : process.env.MIGRATION_NAME
  if (!raw) {
    console.error('[migration:generate] --name=<PascalCaseName> is required')
    process.exit(1)
  }
  if (!/^[A-Z][A-Za-z0-9]*$/.test(raw)) {
    console.error('[migration:generate] name must be PascalCase (e.g. AddUserAvatar)')
    process.exit(1)
  }
  return raw
}

const name = resolveName()

// 1. Bring the target database fully up to date so the diff starts from latest.
const { initDataSource, closeDataSource } = await import('../src/utils/database')
try {
  await initDataSource()
} finally {
  await closeDataSource()
}

// 2. Diff entity metadata against the (now current) schema.
const { AppDataSource } = await import('../src/utils/database')
try {
  await AppDataSource.initialize()
  const { upQueries, downQueries } = await AppDataSource.driver.createSchemaBuilder().log()
  if (upQueries.length === 0) {
    console.log('[migration:generate] no schema changes detected')
    process.exit(1)
  }

  const timestamp = Date.now()
  const className = `${name}${timestamp}`
  const file = resolve(import.meta.dirname, '../../src/migrations', `${timestamp}-${name}.ts`)

  // 按依赖顺序重排 down 语句：约束 → 索引 → 表 → 枚举类型。
  // SchemaBuilder 的原始输出会把 DROP TYPE 排在 DROP TABLE 之前，PG 因依赖拒绝执行。
  const orderedDown = [
    ...downQueries.filter((q) => /DROP CONSTRAINT/i.test(q.query)),
    ...downQueries.filter((q) => /DROP INDEX/i.test(q.query)),
    ...downQueries.filter((q) => /DROP TABLE/i.test(q.query)),
    ...downQueries.filter(
      (q) => !/DROP CONSTRAINT|DROP INDEX|DROP TABLE/i.test(q.query),
    ),
  ]

  const render = (queries: { query: string }[]): string =>
    queries.map((q) => `  ${JSON.stringify(q.query.replace(/\s+/g, ' ').trim())},`).join('\n')

  const content = `import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by \`pnpm migration:generate --name=${name}\` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class ${className} implements MigrationInterface {
  name = '${className}'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
${render(upQueries)}
]

const DOWN: string[] = [
${render(orderedDown)}
]
`
  writeFileSync(file, content)
  console.log(
    `[migration:generate] wrote ${file} (${upQueries.length} up / ${downQueries.length} down)`,
  )
  console.log('[migration:generate] NEXT: register the class in src/migrations/index.ts')
} finally {
  if (AppDataSource.isInitialized) await AppDataSource.destroy()
}
