import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=Init` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class Init1787934397009 implements MigrationInterface {
  name = 'Init1787934397009'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  "CREATE TYPE \"public\".\"user_role_enum\" AS ENUM('super_admin', 'admin')",
  "CREATE TYPE \"public\".\"user_status_enum\" AS ENUM('active', 'inactive')",
  "CREATE TABLE \"users\" (\"id\" SERIAL NOT NULL, \"username\" character varying(50) NOT NULL, \"password_hash\" character varying(255) NOT NULL, \"email\" character varying(100), \"role\" \"public\".\"user_role_enum\" NOT NULL DEFAULT 'admin', \"status\" \"public\".\"user_status_enum\" NOT NULL DEFAULT 'active', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"pk_users\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX \"uq_users_username\" ON \"users\" (\"username\")",
  "CREATE TYPE \"public\".\"lottery_mode_enum\" AS ENUM('offline', 'online')",
  "CREATE TYPE \"public\".\"activity_status_enum\" AS ENUM('draft', 'active', 'ended')",
  "CREATE TABLE \"activities\" (\"id\" SERIAL NOT NULL, \"name\" character varying(100) NOT NULL, \"description\" text, \"lottery_mode\" \"public\".\"lottery_mode_enum\" NOT NULL, \"start_time\" TIMESTAMP, \"end_time\" TIMESTAMP, \"status\" \"public\".\"activity_status_enum\" NOT NULL DEFAULT 'draft', \"settings\" jsonb DEFAULT '{}', \"webhook_id\" character varying(50), \"webhook_token\" character varying(255), \"created_by\" integer, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"pk_activities\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX \"uq_activities_webhook_id\" ON \"activities\" (\"webhook_id\")",
  "CREATE TABLE \"prizes\" (\"id\" SERIAL NOT NULL, \"activity_id\" integer NOT NULL, \"name\" character varying(100) NOT NULL, \"description\" text, \"total_quantity\" integer NOT NULL DEFAULT '0', \"remaining_quantity\" integer NOT NULL DEFAULT '0', \"probability\" numeric(5,4) NOT NULL DEFAULT '0', \"sort_order\" integer DEFAULT '0', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"pk_prizes\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX \"idx_prizes_activity\" ON \"prizes\" (\"activity_id\")",
  "CREATE TYPE \"public\".\"lottery_code_status_enum\" AS ENUM('unused', 'used', 'invalid')",
  "CREATE TABLE \"lottery_codes\" (\"id\" SERIAL NOT NULL, \"activity_id\" integer NOT NULL, \"code\" character varying(50) NOT NULL, \"status\" \"public\".\"lottery_code_status_enum\" NOT NULL DEFAULT 'unused', \"participant_info\" jsonb, \"used_at\" TIMESTAMP, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"pk_lottery_codes\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX \"uq_lottery_codes_activity_code\" ON \"lottery_codes\" (\"activity_id\", \"code\")",
  "CREATE TYPE \"public\".\"signature_status_enum\" AS ENUM('unsigned', 'signed')",
  "CREATE TABLE \"lottery_records\" (\"id\" SERIAL NOT NULL, \"activity_id\" integer NOT NULL, \"lottery_code_id\" integer NOT NULL, \"prize_id\" integer, \"is_winner\" boolean NOT NULL DEFAULT false, \"operator_id\" integer, \"ip_address\" character varying(45), \"user_agent\" text, \"signature_key\" character varying(512), \"signature_url\" text, \"signed_at\" TIMESTAMP, \"signature_status\" \"public\".\"signature_status_enum\" NOT NULL DEFAULT 'unsigned', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"pk_lottery_records\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX \"idx_lottery_records_lottery_code\" ON \"lottery_records\" (\"lottery_code_id\")",
  "CREATE INDEX \"idx_lottery_records_activity\" ON \"lottery_records\" (\"activity_id\")",
  "CREATE TABLE \"operation_logs\" (\"id\" SERIAL NOT NULL, \"user_id\" integer, \"operation_type\" character varying(50) NOT NULL, \"operation_detail\" text, \"target_type\" character varying(50), \"target_id\" integer, \"ip_address\" character varying(45), \"user_agent\" text, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"pk_operation_logs\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX \"idx_operation_logs_created\" ON \"operation_logs\" (\"created_at\")",
  "CREATE INDEX \"idx_operation_logs_user\" ON \"operation_logs\" (\"user_id\")",
  "ALTER TABLE \"activities\" ADD CONSTRAINT \"fk_activities_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION",
  "ALTER TABLE \"prizes\" ADD CONSTRAINT \"fk_prizes_activity\" FOREIGN KEY (\"activity_id\") REFERENCES \"activities\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION",
  "ALTER TABLE \"lottery_codes\" ADD CONSTRAINT \"fk_lottery_codes_activity\" FOREIGN KEY (\"activity_id\") REFERENCES \"activities\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION",
  "ALTER TABLE \"lottery_records\" ADD CONSTRAINT \"fk_lottery_records_activity\" FOREIGN KEY (\"activity_id\") REFERENCES \"activities\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION",
  "ALTER TABLE \"lottery_records\" ADD CONSTRAINT \"fk_lottery_records_lottery_code\" FOREIGN KEY (\"lottery_code_id\") REFERENCES \"lottery_codes\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION",
  "ALTER TABLE \"lottery_records\" ADD CONSTRAINT \"fk_lottery_records_prize\" FOREIGN KEY (\"prize_id\") REFERENCES \"prizes\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION",
  "ALTER TABLE \"lottery_records\" ADD CONSTRAINT \"fk_lottery_records_operator\" FOREIGN KEY (\"operator_id\") REFERENCES \"users\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION",
  "ALTER TABLE \"operation_logs\" ADD CONSTRAINT \"fk_operation_logs_user\" FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION",
]

// 手工审查调整：按依赖顺序排列（约束 → 索引 → 表 → 枚举类型），
// 生成器原始输出把 DROP TYPE 排在 DROP TABLE 之前，PG 会因依赖拒绝执行
const DOWN: string[] = [
  "ALTER TABLE \"activities\" DROP CONSTRAINT \"fk_activities_created_by\"",
  "ALTER TABLE \"prizes\" DROP CONSTRAINT \"fk_prizes_activity\"",
  "ALTER TABLE \"lottery_codes\" DROP CONSTRAINT \"fk_lottery_codes_activity\"",
  "ALTER TABLE \"lottery_records\" DROP CONSTRAINT \"fk_lottery_records_activity\"",
  "ALTER TABLE \"lottery_records\" DROP CONSTRAINT \"fk_lottery_records_lottery_code\"",
  "ALTER TABLE \"lottery_records\" DROP CONSTRAINT \"fk_lottery_records_prize\"",
  "ALTER TABLE \"lottery_records\" DROP CONSTRAINT \"fk_lottery_records_operator\"",
  "ALTER TABLE \"operation_logs\" DROP CONSTRAINT \"fk_operation_logs_user\"",
  "DROP INDEX \"public\".\"uq_users_username\"",
  "DROP INDEX \"public\".\"uq_activities_webhook_id\"",
  "DROP INDEX \"public\".\"idx_prizes_activity\"",
  "DROP INDEX \"public\".\"uq_lottery_codes_activity_code\"",
  "DROP INDEX \"public\".\"idx_lottery_records_lottery_code\"",
  "DROP INDEX \"public\".\"idx_lottery_records_activity\"",
  "DROP INDEX \"public\".\"idx_operation_logs_created\"",
  "DROP INDEX \"public\".\"idx_operation_logs_user\"",
  "DROP TABLE \"users\"",
  "DROP TABLE \"activities\"",
  "DROP TABLE \"prizes\"",
  "DROP TABLE \"lottery_codes\"",
  "DROP TABLE \"lottery_records\"",
  "DROP TABLE \"operation_logs\"",
  "DROP TYPE \"public\".\"user_role_enum\"",
  "DROP TYPE \"public\".\"user_status_enum\"",
  "DROP TYPE \"public\".\"lottery_mode_enum\"",
  "DROP TYPE \"public\".\"activity_status_enum\"",
  "DROP TYPE \"public\".\"lottery_code_status_enum\"",
  "DROP TYPE \"public\".\"signature_status_enum\"",
]
