import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=AddLotteryCodeIsTest` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class AddLotteryCodeIsTest1788417306770 implements MigrationInterface {
  name = 'AddLotteryCodeIsTest1788417306770'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  'ALTER TABLE "lottery_codes" ADD "is_test" boolean NOT NULL DEFAULT false',
  // 一活动至多一个测试码（TypeORM 装饰器表达不了部分索引，手工补充）
  'CREATE UNIQUE INDEX "uq_lottery_codes_activity_is_test" ON "lottery_codes" ("activity_id") WHERE "is_test" = true',
]

const DOWN: string[] = [
  'DROP INDEX "uq_lottery_codes_activity_is_test"',
  'ALTER TABLE "lottery_codes" DROP COLUMN "is_test"',
]
