import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=AddSystemSettings` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class AddSystemSettings1788091777967 implements MigrationInterface {
  name = 'AddSystemSettings1788091777967'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  'CREATE TABLE "system_settings" ("key" character varying(100) NOT NULL, "value" text NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b1b5bc664526d375c94ce9ad43d" PRIMARY KEY ("key"))',
]

const DOWN: string[] = ['DROP TABLE "system_settings"']
