import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=SignatureToPgsql` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class SignatureToPgsql1788027007612 implements MigrationInterface {
  name = 'SignatureToPgsql1788027007612'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  'ALTER TABLE "lottery_records" DROP COLUMN "signature_key"',
  'ALTER TABLE "lottery_records" DROP COLUMN "signature_url"',
  'ALTER TABLE "lottery_records" ADD "signature_data" text',
]

const DOWN: string[] = [
  'ALTER TABLE "lottery_records" ADD "signature_key" character varying(512)',
  'ALTER TABLE "lottery_records" ADD "signature_url" text',
  'ALTER TABLE "lottery_records" DROP COLUMN "signature_data"',
]
